apiVersion: v2
name: apollo-service
description: A Helm chart for Apollo Config Service and Apollo Admin Service
type: application
version: 0.2.0
appVersion: 1.8.0
home: https://github.com/ctripcorp/apollo
icon: https://raw.githubusercontent.com/ctripcorp/apollo/master/apollo-portal/src/main/resources/static/img/logo-simple.png
maintainers:
- name: nobodyiam
  email: nobodyiam@gmail.com
  url: https://github.com/nobodyiam
